services:
  # ContextKeeper - Combined Backend + Frontend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped
