version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: contextkeeper
      POSTGRES_PASSWORD: contextkeeper_dev
      POSTGRES_DB: contextkeeper
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contextkeeper -d contextkeeper"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
